### ISSUE TITLE
None of the resources provider creates seems to be importable

### ISSUE THREAD

**Issue by mi1os** [megaport/terraform-provider-megaport#1]
First of all thank you very much for this provider. It is something we were waiting for :) I finally found some time to experiment with it.

I have tried to import our current MCRs and VXCs to terraform as the documentation says it is possible https://registry.terraform.io/providers/megaport/megaport/latest/docs/resources/megaport_mcr#import

However I am unable to do so

```terraform import megaport_mcr.tftest XXX
megaport_mcr.tftest: Importing from ID "XXX"...

Error: resource megaport_mcr doesn't support import
```

I've briefly checked the code and it seems to be because the `Importer` function is not implemented.

**Comment by HammoTime** [comment]
G'day mi1os,

We've put a ticket into the next sprint to take a look and scope it out. Will provide an ETA once we've looked into it further.

Thanks again for letting us know!

Adam Hammond
Megaport DevOps

**Comment by HammoTime** [comment]
@mi1os, I've pushed a new version `v0.1.5` which will allow importing.

**Comment by mi1os** [comment]
Thanks @HammoTime . I have tried to import MCR and I am getting following crash

```2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: panic: runtime error: index out of range [0] with length 0
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5:
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: goroutine 73 [running]:
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: github.com/megaport/terraform-provider-megaport/resource_megaport.resourceMegaportMCRRead(0xc000232770,
0xf2e460, 0xc0002fe760, 0xc000232770, 0x0)
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5:     github.com/megaport/terraform-provider-megaport/resource_megaport/resource_megaport_mcr.go:55 +0x97b
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000435560,
0xc00051a280, 0xf2e460, 0xc0002fe760, 0xc0004c41e8, 0x0, 0x0)
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5:     github.com/hashicorp/terraform-plugin-sdk@v1.9.1/helper/schema/resource.go:460 +0x119
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).
ReadResource(0xc00018ec90, 0x124f320, 0xc00076e4b0, 0xc00007a600, 0xc00018ec90, 0xc00076e4b0, 0xc000612b78)
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5:     github.com/hashicorp/terraform-plugin-sdk@v1.9.1/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0xfbad00,
0xc00018ec90, 0x124f320, 0xc00076e4b0, 0xc00007a5a0, 0x0, 0x124f320, 0xc00076e4b0, 0xc00056a000, 0x108)
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5:     github.com/hashicorp/terraform-plugin-sdk@v1.9.1/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000682900, 0x12591e0, 0xc000001800, 0xc000238600,
0xc000215080, 0x1952bd0, 0x0, 0x0, 0x0)
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5:     google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: google.golang.org/grpc.(*Server).handleStream(0xc000682900, 0x12591e0, 0xc000001800, 0xc000238600, 0x0)
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5:     google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001824c0, 0xc000682900, 0x12591e0, 0xc000001800,
0xc000238600)
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5:     google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-10T13:08:58.017+0100 [DEBUG] plugin.terraform-provider-megaport_v0.1.5:     google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2021-02-10T13:08:58.020+0100 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/megaport/megaport/0.1.5/linux_amd64/terraform-provider-megaport_v0.1.5
pid=60935 error="exit status 2"
```

I am attaching crash.log with obfuscated MCR ID
[crash.log](https://github.com/megaport/terraform-provider-megaport/files/5958045/crash.log)

**Comment by HammoTime** [comment]
G'day @mi1os,

Thanks for the update. I've opened #2 to track this issue. Can you please email me the sample terraform configuration for the MCR, the MCR ID, and whether this was on production or staging. My email address is adam.hammond@megaport.com. 

Adam.

**Comment by HammoTime** [comment]
G'day @mi1os,

I received your email, thanks for sending the info through!

I've found the issue and have made the changes. I just need to update some logic for VXCs before push it up. I hope to have this work done by the end of the day.

Thanks,

Adam.

**Comment by HammoTime** [comment]
Hi @mi1os ,

I've just pushed `v1.0.6` which should now resolve the issues with the MCR import, sorry about that!

I also deep-dived into the other resources today and discovered there's a lot of work into making them importable. I've removed the import documentation on `megaport_aws_connection`, `megaport_azure_connection`, `megaport_gcp_connection`, and `megaport_vxc_connection` to reflect that they won't be immediately available.

We've put a ticket into our backlog and hope to have these other resources importable in the future.

Can you please test the MCR import and let me know how you go?

Thanks,

Adam.

**Comment by mi1os** [comment]
Hi @HammoTime, I can confirm that version 1.6 can successfully import MCRs. Thanks for the note about the aws/azure/gcp connections. I can easily recreate those so it should not affect me. Will give the provider some more testing tomorrow.

**Comment by HammoTime** [comment]
Thanks for the update mi1os. Now that it's working, I'll close this ticket out.

Have a fantastic weekend!

**Comment by wwjn** [comment]
Documentation for the provider still shows 0.1.1 as the suggested version which does not support importing.  It would be good to see this updated to avoid confusion.

```
terraform {
  required_providers {
    megaport = {
      source = "megaport/megaport"
      version = "0.1.1"
    }
  }
}
```

https://github.com/megaport/terraform-provider-megaport/wiki/Configuration
