### ISSUE TITLE
[BUG] Import of MVE is not accurate

### ISSUE THREAD

**Issue by zjaniga** [megaport/terraform-provider-megaport#173]
**Describe the bug**
After importing our MVEs into the statefile and doing a plan, the import seems to be based on an older version, because the vendor_config is not part of it, but it's mandatory parameters (vendor, product_id=image_id, mve_size=product_size) are there one layer above.

**Terraform and Provider Version**
The version of `terraform-provider-megaport` as well as the version of `terraform` you are using.
terraform-provider-megaport: 1.2.0
terraform: 1.8.1

**Terraform File and Steps to Reproduce**
If possible please provide a `.tf` file that can reproduce the issue, along with any changes you made to trigger the issue. If there is an API error that is returned, please provide the `trace_id` so that we can look up the request.
Import an MVE, create the configuration and run a plan:
`
# module.megaport_mve.megaport_mve.mve["IONA-VA1-MVEUS2"] must be replaced
-/+ resource "megaport_mve" "mve" {
      ~ admin_locked           = false -> (known after apply)
      ~ attribute_tags         = {} -> (known after apply)
      ~ buyout_port            = false -> (known after apply)
      ~ cancelable             = true -> (known after apply)
      ~ company_name           = "ION Analytics" -> (known after apply)
      ~ company_uid            = "8af59047-55ee-4c74-8bd3-b07e18fe55f8" -> (known after apply)
      ~ contract_end_date      = "Wednesday, 22-Jul-26 16:00:00 CEST" -> (known after apply)
      ~ contract_start_date    = "Tuesday, 23-Jul-24 14:22:34 CEST" -> (known after apply)
      ~ cost_centre            = null -> (known after apply)
      ~ create_date            = "Tuesday, 23-Jul-24 14:21:35 CEST" -> (known after apply)
      ~ created_by             = "f81730fd-0009-4fce-9196-1a59f9fbd0eb" -> (known after apply)
      + last_updated           = (known after apply)
      ~ live_date              = "Tuesday, 23-Jul-24 14:22:34 CEST" -> (known after apply)
      ~ locked                 = false -> (known after apply)
      ~ market                 = "US" -> (known after apply)
      ~ marketplace_visibility = false -> (known after apply)
      ~ **mve_size**               = "MEDIUM" -> (known after apply)
      ~ **product_id**             = 204831 -> (known after apply)
      ~ product_type           = "MVE" -> (known after apply)
      ~ product_uid            = "029d01cb-0839-485d-b204-b64f151c9463" -> (known after apply)
      ~ provisioning_status    = "LIVE" -> (known after apply)
      ~ secondary_name         = null -> (known after apply)
      ~ terminate_date         = null -> (known after apply)
      ~ usage_algorithm        = "POST_PAID_FIXED" -> (known after apply)
      ~ **vendor**                 = "CISCO" -> (known after apply)
      **+ vendor_config          = { # forces replacement
          + image_id     = 204831 # forces replacement
          + product_size = "MEDIUM" # forces replacement
          + vendor       = "CISCO" # forces replacement
        }**
      ~ virtual                = false -> (known after apply)
      ~ vxc_auto_approval      = false -> (known after apply)
      ~ vxc_permitted          = true -> (known after apply)
        # (4 unchanged attributes hidden)
    }
`

**Additional context**

**Comment by mega-alex** [comment]
Hi there, could you please provide a .tf file to reproduce this issue?

**Comment by zjaniga** [comment]
```
resource "megaport_mve" "mve" {
  product_name         = "IONA-DC4-MVEUS2"
  location_id          = 67
  contract_term_months = 24

  vnics = [
    {
      description = "Data Plane"
    },
    {
      description = "Azure connection"
    },
    {
      description = "AWS connection"
    },
    {
      description = "IONA-DC4-MVEUS2/iBGP"
    },
    {
      description = "Spare interface"
    }
  ]

  vendor_config = {
    vendor       = "CISCO"
    product_size = "MEDIUM"
    image_id     = 204449
  }
}
```

**Comment by zjaniga** [comment]
Thanks for the update!

**Comment by zjaniga** [comment]
Hi @mega-alex , was there any change around the location names?
I cannot import anymore (however it was working before), because it is unable to get the location by name.

Is there a list of locations that the code accepts?

**Comment by MegaportPhilipBrowne** [comment]
Which location were you trying to obtain?  We'll try to replicate the error today.  Thanks!

**Comment by MegaportPhilipBrowne** [comment]
Thanks for letting us know.  Could you please try each of those with one of the following and let us know if you run into any issues?  

```
data "megaport_location" "dub-ix2-name" {
 name = "Digital Realty Dublin DUB2"
}

data "megaport_location" "dub-ix2-sitecode" {
  site_code = "dub-ix2"
}

data "megaport_location" "ash-cs2-name" {
  name = "CoreSite VA1"
}

data "megaport_location" "ash-cs2-sitecode" {
  site_code = "ash-cs2"
}
```

Also, just to clarify are you running into this issue on `v1.2.3`?

Thanks!

**Comment by mega-alex** [comment]
We looked into this one today, it appears we updated our name for the datacenter in the API because Interxion was acquired by Digital Realty, and this just happened to coincide with the provider update. The site code remained the same, and we added the ability to filter by site code in the `megaport_location` resource rather than the name, so this should fix this issue going forward.

**Comment by zjaniga** [comment]
Just re-imported the MVEs again, and the state file still does not contains the vendor_config part.
And I upgraded to the latest 1.2.4 version already.

**Comment by MegaportPhilipBrowne** [comment]
Thanks for letting us know.  Just to clarify, you are including `vendor_config` in your plan upon importing, right?  If so, that field should definitely be showing up in the state following import.  However, this is an input only field, so it will not be affected by any read requests of the MVE in the Megaport API -- it essentially will just be what's included in the plan for the resource you wish to import.  Could you please provide the initial plan for import and the statefile post import, so we can best replicate your issue and see what's occurring?  Thanks so much!

**Comment by zjaniga** [comment]
I don't think the problem is with my code, after importing the MVE resource, the vendor_config part should be visible in the state file.

Before importing MVE:
`
# module.megaport_mve.megaport_mve.mve will be created
  + resource "megaport_mve" "mve" {
      + admin_locked           = (known after apply)
      + attribute_tags         = (known after apply)
      + buyout_port            = (known after apply)
      + cancelable             = (known after apply)
      + company_name           = (known after apply)
      + company_uid            = (known after apply)
      + contract_end_date      = (known after apply)
      + contract_start_date    = (known after apply)
      + contract_term_months   = 24
      + cost_centre            = (known after apply)
      + create_date            = (known after apply)
      + created_by             = (known after apply)
      + diversity_zone         = (known after apply)
      + last_updated           = (known after apply)
      + live_date              = (known after apply)
      + location_id            = 67
      + locked                 = (known after apply)
      + market                 = (known after apply)
      + marketplace_visibility = (known after apply)
      + mve_size               = (known after apply)
      + product_id             = (known after apply)
      + product_name           = "IONA-DC4-MVEUS2"
      + product_type           = (known after apply)
      + product_uid            = (known after apply)
      + provisioning_status    = (known after apply)
      + secondary_name         = (known after apply)
      + terminate_date         = (known after apply)
      + usage_algorithm        = (known after apply)
      + vendor                 = (known after apply)
      + vendor_config          = {
          + image_id     = 204449
          + product_size = "MEDIUM"
          + vendor       = "CISCO"
        }
      + virtual                = (known after apply)
      + vnics                  = [
          + {
              + description = "Data Plane"
            },
          + {
              + description = "Azure connection"
            },
          + {
              + description = "AWS connection"
            },
          + {
              + description = "IONA-DC4-MVEUS2/iBGP"
            },
          + {
              + description = "Spare interface"
            },
        ]
      + vxc_auto_approval      = (known after apply)
      + vxc_permitted          = (known after apply)
    }
`

After imported:
`
# module.megaport_mve.megaport_mve.mve will be updated in-place
  ~ resource "megaport_mve" "mve" {
      ~ contract_start_date    = "Thursday, 18-Jul-24 17:05:04 CEST" -> (known after apply)
      ~ cost_centre            = null -> (known after apply)
      + last_updated           = (known after apply)
      ~ live_date              = "Thursday, 18-Jul-24 17:05:04 CEST" -> (known after apply)
      ~ provisioning_status    = "LIVE" -> (known after apply)
      ~ terminate_date         = null -> (known after apply)
      + vendor_config          = {
          + image_id     = 204449
          + product_size = "MEDIUM"
          + vendor       = "CISCO"
        }
        # (27 unchanged attributes hidden)
    }
`

Statefile:
`
resource "megaport_mve" "mve" {
    admin_locked           = false
    attribute_tags         = {}
    buyout_port            = false
    cancelable             = true
    company_name           = "ION Analytics"
    company_uid            = "8af59047-55ee-4c74-8bd3-b07e18fe55f8"
    contract_end_date      = "Saturday, 18-Jul-26 16:00:00 CEST"
    contract_start_date    = "Thursday, 18-Jul-24 17:05:04 CEST"
    contract_term_months   = 24
    cost_centre            = ""
    create_date            = "Thursday, 18-Jul-24 17:03:27 CEST"
    created_by             = "f81730fd-0009-4fce-9196-1a59f9fbd0eb"
    diversity_zone         = "red"
    live_date              = "Thursday, 18-Jul-24 17:05:04 CEST"
    location_id            = 67
    locked                 = false
    market                 = "US"
    marketplace_visibility = false
    mve_size               = "MEDIUM"
    product_id             = 204449
    product_name           = "IONA-DC4-MVEUS2"
    product_type           = "MVE"
    product_uid            = "d3aa4fc1-ac4c-4f94-a21c-4026614ae131"
    provisioning_status    = "LIVE"
    secondary_name         = ""
    terminate_date         = ""
    usage_algorithm        = "POST_PAID_FIXED"
    vendor                 = "CISCO"
    virtual                = false
    vnics                  = [
        {
            description = "Data Plane"
        },
        {
            description = "Azure connection"
        },
        {
            description = "AWS connection"
        },
        {
            description = "IONA-DC4-MVEUS2/iBGP"
        },
        {
            description = "Spare interface"
        },
    ]
    vxc_auto_approval      = false
    vxc_permitted          = true
}
`

**Comment by MegaportPhilipBrowne** [comment]
Thanks for this. I understand your concern about the `vendor_config` not showing immediately following import. The reason for this is that it is an input-only field provided by the user for creation and updates that is not returned on read responses of the MVE from the Megaport API. However, if the `vendor_config` is included in the plan following import, it will be incorporated into the state file on the next apply, as is shown in your logging: 

```# module.megaport_mve.megaport_mve.mve will be updated in-place
  ~ resource "megaport_mve" "mve" {
      ~ contract_start_date    = "Thursday, 18-Jul-24 17:05:04 CEST" -> (known after apply)
      ~ cost_centre            = null -> (known after apply)
      + last_updated           = (known after apply)
      ~ live_date              = "Thursday, 18-Jul-24 17:05:04 CEST" -> (known after apply)
      ~ provisioning_status    = "LIVE" -> (known after apply)
      ~ terminate_date         = null -> (known after apply)
      + vendor_config          = {
          + image_id     = 204449
          + product_size = "MEDIUM"
          + vendor       = "CISCO"
        }
        # (27 unchanged attributes hidden)
    }
```

In addition, because you are not changing the MVE image ID, vendor, or size of the MVE, the import will not affect the state or underlying configuration of the MVE resource.  While the `vendor_config` is not showing immediately after import, it's not changing the underlying configuration for the deployed MVE, it's still going to be a Medium Cisco MVE with the Image ID of 204449.  

If it does not show up in the statefile following the subsequent apply, please let us know. And please feel free to reach out if you have any additional questions or concerns!

**Comment by zjaniga** [comment]
Thank you for your explanation!
I just applied the changes and seems nothing has been broken :)
